### ISSUE TITLE
Amazing project~

### ISSUE THREAD

**Issue by sonictl** [colonelwatch/pi-sph-fluid#1]
Hello, very glad to see this sph-fluid proj. and this is what i was dreaming to make! Ask you a question: what is the minimum hardware/computing resources that was required for running this fluid simulation? Is it possible to run it on micro-chip such as MIPS or ESP32? 

Making the board smaller and making the screen larger (more fluid) will add more value onto this proj.

Anyway, Amazing, Cool!! and thank you for your knowledge-sharing !!

**Comment by colonelwatch** [comment]
Hello, and you're welcome. This was something I wanted to make for years, and I put a lot of effort into showing my work with this one. :)

To answer your question, unfortunately the minimum hardware on this project is a Raspberry Pi 4. I think running SPH on an ESP32 would be extremely challenging, if not impossible. (If it is possible, it definitely would have to use a more sophisticated "incompressible SPH" technique, not the "weakly compressible SPH" featured in this project.)

Have you considered cellular automata fluids yet? That would be the water you'd see in a falling sand game like Powder Toy, and I can easily see that being achieved on an ESP32. You can also follow other people who have done it on PCs already. And if you want to go the extra mile, here's an idea from me: simulating pressure is a kind of hidden trick to really believable fluids. Some projects do it, but others don't. For an example of one that does, here's this interview I just found from the developer of Dwarf Fortress about simulating pressure using cellular automata: https://www.gamedeveloper.com/design/interview-the-making-of-dwarf-fortress. Though, I don't know how well the method mentioned in the interview would actually work for you.
